name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_ENV"
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint && yarn prettier:check
      - name: E2e
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          browser: chrome
